name: nodejs deploy on the docker instance
on: 
  push: 
   branches: 
     - dev
jobs: 
  build: 
   runs-on: self-hosted
   steps: 
     - name: Git-checkout
       uses: actions/checkout@v4
     - name: docker-packages
       run: | 
         sudo apt-get update -y
         sudo apt install docker.io -y
         sudo usermod -aG docker ubuntu
         sudo chmod 777 /var/run/docker.sock
         sudo systemctl restart docker
     - name: Build dockerfile into docker images
       run: | 
         docker build -t httpd:v3 . 
         docker run -itd --name webserver -p 80:80 httpd:v3
