name: nodejs-workflow
on: push
jobs: 
    first-job: 
        runs-on: ubuntu-latest
        steps: 
            - name: git-checkout
              uses: actions/checkout@v4.1.7
            - name: npm-lint
              run: npm run lint
              