name: React-project
on: [push, workflow_dispatch]
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
     - name: git checkout
       uses: actions/checkout@v4
     - name: setup nodejs
       uses: actions/setup-node@v4
       with: 
         node-version: 18
     - name: npm installation
       run: | 
        sudo apt-get update -y
        npm install
        npm run build
        npm test
